### ISSUE TITLE
d2xx: edge triggering is not supported

### ISSUE THREAD

**Issue by ldrrp** [periph/extra#7]
When will edge triggering be supported. How am i supposed to use a button with an ft232h

**Comment by ardnew** [comment]
I don't believe interrupt edge detection is something the D2XX driver supports in _any_ mode, inherently because of its vendor class USB protocol. 

You can't guarantee delivery or ordering of interrupts if they are encapsulated in USB packets.

The best you could do is polling. Just dispatch a goroutine that constantly reads a pin and compares its previous value.

Also see:
- https://www.ftdichip.com/Support/Knowledgebase/an232b_04needhandshake.htm?zoom_highlightsub=Interrupt
- https://www.ftdichip.com/Support/Knowledgebase/an232b_04datacompare.htm?zoom_highlightsub=Interrupt

**Comment by maruel** [comment]
Moved to https://github.com/periph/host/issues/5

FYI, periph.io/x/host/v3@v3.7.0 has native FTDI support so normal periph just works.
